version: '3'
services:
  doc:
    image: victorialabs/doccumentation
    ports:
      - "8080:3500"

    restart: always

    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doc.rule=Host(`test.mazbaz.fr`)"
      - "traefik.http.routers.doc.entrypoints=websecure"
      - "traefik.http.routers.doc.tls.certresolver=leresolver"

networks:
  default:
  traefik:
    external: true